// Code generated by MockGen. DO NOT EDIT.
// Source: mosaic/mosaic.go
//
// Generated by this command:
//
//      mockgen -source mosaic/mosaic.go -package mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
        reflect "reflect"

        gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
        ctrl     *gomock.Controller
        recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
        mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
        mock := &MockCommand{ctrl: ctrl}
        mock.recorder = &MockCommandMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
        return m.recorder
}

// Execute mocks base method.
func (m *MockCommand) Execute(command string, args ...string) error {
        m.ctrl.T.Helper()
        varargs := []any{command}
        for _, a := range args {
                varargs = append(varargs, a)
        }
        ret := m.ctrl.Call(m, "Execute", varargs...)
        ret0, _ := ret[0].(error)
        return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandMockRecorder) Execute(command any, args ...any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        varargs := append([]any{command}, args...)
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommand)(nil).Execute), varargs...)
}
